export const ERROR_CODES = {
    INVALID_TOKEN: "INALID_TOKEN",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    TOKEN_EXPIRED: "TOKEN_EXPIRED",
    WRONG_PASSWORD: "WRONG_PASSWORD",
    VALIDAITON_ERROR: "VALIDATION_ERROR",
    USER_EXIST: "USER_EXIST_ERROR",
    USER_NOT_EXIST: "USER_NOT_EXIST",
    ARDUINO_SERVER_ERROR: "ARDUINO_SERVER_ERROR"
};